name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install aiosqlite  # for testing

      # # Run tests
      # - name: Run tests
      #   env:
      #     DATABASE_URL: "sqlite:///:memory:"
      #   run: |
      #     pytest


      # Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          echo $DIGITALOCEAN_ACCESS_TOKEN | docker login registry.digitalocean.com --username _ --password-stdin

      # Build Docker Image with Git commit hash as tag
      - name: Build Docker image
        env:
          COMMIT_HASH: ${{ github.sha }}
        run: |
          docker build -t registry.digitalocean.com/teamfilmtinder/filmtinder-api:${COMMIT_HASH} -t registry.digitalocean.com/teamfilmtinder/filmtinder-api:latest .

      # Push Docker Image
      - name: Push Docker image to DigitalOcean
        run: |
          docker push --all-tags registry.digitalocean.com/teamfilmtinder/filmtinder-api

      # Deploy to DigitalOcean Kubernetes
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
        
      - name: Configure kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBE_CONFIG_DATA}" > $HOME/.kube/config

      - name: Update Deployment with New Image
        env:
          COMMIT_HASH: ${{ github.sha }}
        run: |
          kubectl set image deployment/website website=registry.digitalocean.com/teamfilmtinder/filmtinder-api:${COMMIT_HASH} -n filmtinder-api-db
